import{a as d,i as m,S as g}from"./assets/vendor-43ae9e23.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const f="https://api.thecatapi.com/v1",y=`${f}/breeds`,b=`${f}/images/search`;d.defaults.headers.common["x-api-key"]="live_VYbKMLMNU1YPqRUi9zgtBMrP5nI3b3RK1KjJIZalHGbhDzMvyGrx4A9vCcMdLz52";const L=async()=>{try{return(await d.get(y)).data}catch(e){console.error("Error fetching breeds: ",e)}},v=async e=>{try{return(await d.get(b,{params:{breed_ids:e}})).data}catch(r){console.error("Error fetching breed: ",r)}},p={hidden:"hidden"},i=(e,r)=>{r?e.classList.add(p.hidden):e.classList.remove(p.hidden)},a=document.querySelector(".loading-container"),u=document.querySelector(".select"),l=document.querySelector(".info-container"),S=e=>{const r='<option data-placeholder="true"></option>',o=e.map(n=>`<option value="${n.id}">${n.name}</option>`).join("");u.insertAdjacentHTML("afterbegin",`${r}${o}`),new g({select:"#selectElement"})},h=(e,r)=>{m.error({title:r?"Error":"Success",message:e,position:"topRight"})},$=async()=>{i(a,!1);const e=await L();i(a,!0),e&&e.length?(i(u,!1),S(e)):h("Sorry, there is an error loading breed info. Try reloading the page.",!0)};$();u.addEventListener("change",async e=>{i(a,!1),l.innerHTML="";const r=e.target.value,o=await v(r);if(i(a,!0),o&&o.length){const{name:n,description:t,temperament:s}=o[0].breeds[0],c=o[0].url;l.insertAdjacentHTML("afterbegin",`
        <img class="img" src="${c}" alt="${n}" width="400" height="320">
        <div class="text-container">
        <h2>${n}</h2>
        <p>${t}</p>
        <p>
        <span class="bold">Temperament:</span>
         ${s}</p>
        </div>
      `),i(l,!1)}else h("Sorry, there is an error loading cat info. Try reloading the page.",!0)});
//# sourceMappingURL=commonHelpers.js.map
